require(plyr)
require(dummies)
require(stats4)
require(reshape)


# This script generates xtabs for the moves-to and moves-from variables
# in the PSID file generated by get_complete.py
# See get_complete.py for more info on the construction of the PSID file
# 
# Dependencies: 
#    get_complete.py: generates PSID file 
#    logit_by_hand.R: contains function to generate agebucket variable
#
# Output: 
#   xtabs_indwt.csv: crosstabs of weighted move counts by transition to/from category
#


selectPeriod <- function(df, years) { 
# Isolates observations that fall into a select year range only
#
# Args: 
#    df: a PSID dataframe 
#    years: vector; contains years to isolate
#
# Returns: 
#    output: a PSID dataframe with obs that fall into select years
    output <- df[df$year %in% years,]
    return(output)      
}

tosrhousingShare <- function(df) {
# For a given age bucket, calculates the moves to senior living from SF/ shared 
# as a share of total moves     
#
# Args:
#    df: a PSID dataframe with agebucket and housing transition vars and weights
#    varname: the column name of the output dataframe
# Returns: 
#    output: a weighted share of transitions to senior living made from SF/Shared as part of total moves
# 
# Error handling: 
# Change all values of variable moved to 0 or 1 
    data[!(df$moved %in% c(0,1)), 'moved'] <- 0
    totmoves = sum(df$moved * df$indweight)  
    #inplace.to.sr <- sum(df[(df$trans_to == "Senior") & (df$trans_from %in% c('SF', 'Shared')), 'indweight'])
    inplace.to.sfsh <- sum(df[(df$trans_to %in% c("SF", "Shared")) & (df$trans_from %in% c('SF', 'Shared', 'MF','Senior')), 'indweight'])    
    #output <- inplace.to.sr/totmoves
    output <- inplace.to.sfsh / totmoves
    return(output)  
}




"# Source housekeeping functions
dir <- M:/senior living/code/senior-living/analysis/logit/housekeeping.R"
source(dir)

# Read in the data
datadir <- /users/shruthivenkatesh/documents/senior living/complete_st-logit.csv
#datadir <- "M:/senior living/data/psid data/complete_st.csv"
#data <- read.csv(datadir)

# Generate agebucket variable
edges <- seq(55, 100, 5)
data <- data[data$age2 >= 55, ]
data <- getAgeBucket(data, edges)

# Clean up moved variable: values 5, 8, 9 coded to "No move" 
#data[data$moved %in% c(5, 8, 9), 'moved'] = 0 

# Get share of moves to senior housing that are made FROM shared or SF housing
# Across all time periods in a single table by 5-year age bucket
period1df <- selectPeriod(data, seq(1968, 1984))
period2df <- selectPeriod(data, seq(1985, 1995))
period3df <- selectPeriod(data, c(1996, seq(1997, 2011, 2)))

total <- rename(ddply(data, 'agebucket', tosrhousingShare, .parallel=TRUE), c("V1"="1968-2011"))
period1 <- rename(ddply(period1df, 'agebucket', tosrhousingShare, .parallel=TRUE), c("V1"="1968-1984"))
period2 <- rename(ddply(period2df, 'agebucket', tosrhousingShare, .parallel=TRUE), c("V1"="1985-1995"))
period3 <- rename(ddply(period3df, 'agebucket', tosrhousingShare, .parallel=TRUE), c("V1"="1996-2011"))

complete <- join_all(list(total, period1, period2, period3))
#write.csv(complete, "M:/xtabs_indwtv2.csv", row.names=FALSE)

# Get crosstabs of to/from moving categories by 5-year age buckets
# Write each crosstab to same csv file
output = "M:/Senior living/data/psid data/xtabs_indwt2.csv"
agedf <- data.frame(agebucket=edges, inplace.to.sr=rep(0,length(edges)))
"




